### ISSUE TITLE
其实sublime里面有这个功能。

### ISSUE THREAD

**Issue by zhea55** [Wuage-FE/GotoLast#1]
I know what you did last summer
================================

While `undo` and `soft-undo` functionalities are great, they are only limited
to the view you are working with. What if you want to see your cursor movement
across the tabs?

Well, we have a solution here.

* Jump back in history - `Alt + -`
* Jump forward in history - `Alt + Shift + -`

可以使用sublime tutor进行练习。

**Comment by diqye2014** [comment]
这个跟sublime内置的goto-back功能是不一样的

1. goto-back 是记录所有光标的位置（无论是否有修改）
2. goto-back 维护的是一个列表  这个定位的是一个位置 

看具体的场景去使用  如果你想要一个很确定的位置（即最后一次修改）比较适合用这个，如果想要一个列表适合使用内置的功能

**Comment by zhea55** [comment]
回到最后一次编辑过的位置？

ctrl-z还原一下就知道了。

**Comment by diqye2014** [comment]
ctrl-z只适用于当前编辑文件 而且还有副作用（会回退你最后一次编辑的东西）。
